meta_product_name: "VVAIS"
meta_title: "VVAIS | Academia de Innovaci칩n Social"
meta_description: "Visi칩n Venezuela - Academia de Innovaci칩n Social: empoderando a los m치s vulnerables y transformando comunidades."
meta_image: "v-logo.png" # should exist in `app/assets/images/`
