meta_product_name: "VVAIS"
meta_title: "Visión Venezuela"
meta_description: "Academia de Innovación Social: empoderando a muchos y transformado comunidades"
meta_image: "v-logo.png" # should exist in `app/assets/images/`
